class classname:
    #some functions and variables
    #function--used to perform the specific activity
    #variables--data(memory)

In [11]:
def test():
    print("test() for function")
    return
test()

test() for function


In [2]:
class demo:
    def test(self):
        print("test() for the class and method")
        return
obj=demo()
obj.test()
    

test() for the class and method


In [3]:
class demo1:
    def fact(self,n):
        #return the factorial
        fact=1
        while(n!=0):
            fact=fact*n
            n=n-1
        return fact
p1=demo1()
p1.fact(5)#120

120

#method
#def test(self,para1,para2)

In [4]:
class demo2:
    def __init__(self,p1,p2):
        self.p1=p1
        self.p2=p2
    def add(self,p1,p2):
        return p1+p2
       
c1=demo2(10,20)
print(c1.add(100,200))


300


In [41]:
#some Inheritance
#parent class
class person(object):
    #construction
    def __init__(self,name):
          self.name=name
    def getName(self):
        return self.name
    def isEmployee(self):
        return False
#derived class
class Employee(person):
    def isemployee(self):
        return True
emp=person("anil")
print(emp.getname(),emp.isemployee())
emp1=person("akhil")
print(emp1.getname(),emp1.isemployee())

AttributeError: 'person' object has no attribute 'getname'

In [13]:
class person(object):
    def __init__(self,name):
        self.name=name
    def getname(self):
        return self.name
    def isemployee(self):
        return False
class employee(person):
    def isemployee(self):
        return True
emp=person("anil")
print(emp.getname(),emp.isemployee())
emp1=person("akhil")
print(emp1.getname(),emp1.isemployee())


anil False
akhil False


In [14]:
lst=[1,2,3,4]
print(lst)

[1, 2, 3, 4]


In [15]:
import numpy as np
lst=[1,2,3,4]
array=np.array(lst)
print(array)

[1 2 3 4]


In [16]:
lst = [1,2,3,4]
array=np.array(lst)
print(array.shape)
print(array.dtype)

(4,)
int32


In [17]:
lst=[1.0,2.5,3.6,9.5]
array=np.array(lst)
print(array.shape)
print(array.dtype)

(4,)
float64


In [18]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1.shape)
a2=np.array([(1,2),(3,4),(5,6)])
print(a2.shape)

(2, 3)
(3, 2)


In [19]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1)
a1.reshape(3,2)

[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [20]:
a1=np.array([(1,2,3)])
a2=np.array([(4,5,6)])
print(np.hstack((a1,a2)))

[[1 2 3 4 5 6]]


In [21]:
a1=np.array([(1,2,3)])
a2=np.array([(4,5,6)])
print(np.vstack((a1,a2)))

[[1 2 3]
 [4 5 6]]


In [22]:
a1=np.random.normal(5,0.5,10)
print(a1)

[4.92414386 4.67453028 3.91337621 4.69566136 4.96990893 4.77726092
 5.44239304 4.96072178 3.96797638 4.76203162]


In [23]:
#numpy.zero() and numpy.one()
# generate an array with all zeros----numpy.zeros()
#numpy.zero(shape,dtype=float,order='c')
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [24]:
np.zeros((2,2),dtype=np.int64)

array([[0, 0],
       [0, 0]], dtype=int64)

In [25]:
np.ones((4,3),dtype=np.int64)


array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int64)

In [26]:
A=np.matrix(np.ones((4,4),dtype=np.int64))
print(A)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [27]:
A=np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(A)[2]=5
print(A)

[[1 1 1 1]
 [1 1 1 1]
 [5 5 5 5]
 [1 1 1 1]]


In [28]:
A=np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(A)[1][3]=4
np.asarray(A)[3][3]=16
print(A)

[[ 1  1  1  1]
 [ 1  1  1  4]
 [ 1  1  1  1]
 [ 1  1  1 16]]


In [29]:
import numpy as np
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
np.arange(1,100,9)

array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

In [31]:
np.arange(2,20,2)
np.arange(1,25,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [32]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1)

[[1 2 3]
 [4 5 6]]


In [33]:
a1=np.array([(1,2,3),(4,5,6)])
print("first row:",a1[0])

first row: [1 2 3]


In [34]:
a2=np.array([(1,2,3),(4,5,6)])
print("second row:",a2[1])

second row: [4 5 6]


In [35]:
a1=np.array([(1,2,3),(4,5,6)])
print("silcing column:",a1[:,2])

silcing column: [3 6]


In [36]:
a1=np.array([(1,2,3),(4,5,6)])
print("silcing row:",a1[:,1])

silcing row: [2 5]


In [37]:
a1=np.random.normal(5,1,10)
print(a1)
print("Min value=",np.min(a1))
print("Max value=",np.max(a1))
print("Mean value=",np.mean(a1))
print("Median value=",np.median(a1))


[4.11917239 4.52032119 4.53385624 4.89161933 5.28330343 3.03105105
 4.32992012 5.7641068  5.76905506 4.8674235 ]
Min value= 3.0310510465562537
Max value= 5.7690550589160825
Mean value= 4.710982910877843
Median value= 4.700639867187901


In [38]:
c1=np.array([1,2])
c2=np.array([4,5])
np.dot(c1,c2)

14

In [39]:
c1=np.array([(1,2),(3,4)])
c2=np.array([(3,4),(1,2)])
np.dot(c1,c2)

array([[ 5,  8],
       [13, 20]])

In [40]:
b1=np.array([(1,5),(6,9)])
b2=np.array([(1,3),(1,6)])
np.matmul(b1,b2)

array([[ 6, 33],
       [15, 72]])